# project
#####################
POST http://localhost:8000/api/v1/project/
Content-Type: application/json

{ "name": "str",
  "latitude": 11.1,
  "longitude": 11.2
}

######################
GET http://localhost:8000/api/v1/project/
Content-Type: application/json



######################
PUT http://localhost:8000/api/v1/project/4/
Content-Type: application/json

{ 
  "name": "msk",
  "latitude": 0.1,
  "longitude": 11.2 
}


######################
DELETE  http://localhost:8000/api/v1/project/8/
Content-Type: application/json



######################
# measurement
######################
POST http://localhost:8000/api/v1/measurement/
Content-Type: application/json

{ 
  "value": 133.1,
  "project": 7,
  "screen" : "d:\\m.jpg"
 }

######################
GET http://localhost:8000/api/v1/measurement/
Content-Type: application/json



######################
PUT http://localhost:8000/api/v1/measurement/7/
Content-Type: application/json

{ 
  "value": 22.7,
  "project": 7
}

######################
DELETE  http://localhost:8000/api/v1/measurement/7/
Content-Type: application/json

