# Generated by Django 3.2.8 on 2021-10-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='screen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
